Traceback (most recent call last):
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jacobkoehler/opt/anaconda3/envs/for_ds/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.datasets import load_boston, load_diabetes, load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns = iris.feature_names)
iris.head()
------------------

[0;31m--------------------------------------------[0m
[0;31mNameError[0m  Traceback (most recent call last)
[0;32m<ipython-input-1-c9c8ed0a7770>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mdatasets[0m [0;32mimport[0m [0mload_boston[0m[0;34m,[0m [0mload_diabetes[0m[0;34m,[0m [0mload_iris[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0miris[0m [0;34m=[0m [0mload_iris[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0miris[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0miris[0m[0;34m.[0m[0mdata[0m[0;34m,[0m [0mcolumns[0m [0;34m=[0m [0miris[0m[0;34m.[0m[0mfeature_names[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0miris[0m[0;34m.[0m[0mhead[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

